# wrangler.toml
name = "photo-portfolio"
main = "src/index.ts"
compatibility_date = "2023-11-10"

# Set up R2 binding
[[r2_buckets]]
binding = "PORTFOLIO_BUCKET"
bucket_name = "photo-portfolio-images"
preview_bucket_name = "photo-portfolio-images-dev"

# Define routes - use proper format for Cloudflare Workers
# Note: Route patterns are specified correctly in the [[routes]] section 
[[routes]]
pattern = "/static/*"
zone_name = "photo-portfolio-ew8.pages.dev"  # Replace with your actual domain

# Workers now require a script entry point
[build]
command = "npm run build"
[build.upload]
format = "service-worker"